const LOAD_COMMENT = "LOAD_COMMENT"
const DELETE_COMMENT = "DELETE_COMMENT"
const ADD_COMMENT = "ADD_COMMENT"
const UPDATE_COMMENT = "UPDATE_COMMENT"
export { LOAD_COMMENT, DELETE_COMMENT, ADD_COMMENT, UPDATE_COMMENT }