const LOAD_BLOG = "LOAD_BLOG"
const ADD_BLOG = "ADD_BLOG"
const DELETE_BLOG = "DELETE_BLOG"
const UPDATE_BLOG = "UPDATE_BLOG"
const LOAD_COMMENT = "LOAD_COMMENT"
const DELETE_COMMENT = "DELETE_COMMENT"
const ADD_COMMENT = "ADD_COMMENT"
const UPDATE_COMMENT = "UPDATE_COMMENT"
export { LOAD_BLOG, ADD_BLOG, DELETE_BLOG, UPDATE_BLOG, LOAD_COMMENT, DELETE_COMMENT, ADD_COMMENT, UPDATE_COMMENT }